### ISSUE TITLE
Observation.text: max allowed = 0 validation error is available in qa.html even after removing text property  from the respective instance 

### ISSUE THREAD

**Issue by kalleo1996** [HL7/fhir-shorthand#140]
in the Example instances , even after removing the text property related inputs in the instance , still gives this error, and seems it getting added automatically, is there anything that can be done with fhir shorthand to this matter?
![image](https://user-images.githubusercontent.com/38199192/211966377-5b535585-71a4-4c95-a908-9872583b90c3.png)

**Comment by grahamegrieve** [comment]
This is not a shorthand issue. See https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html for how to deal with narrative.

**Comment by cmoesel** [comment]
@kalleo1996 - See the SUSHI config [exhaustive example](https://fshschool.org/docs/sushi/configuration/#exhaustive-example) for an example of how to use the parameters Grahame linked to above.
