### ISSUE TITLE
SUSHI doc needs to be updated to reflect new output folders

### ISSUE THREAD

**Issue by cmoesel** [HL7/fhir-shorthand#28]
The documentation here still indicates a `resources` folder rather than the separate `profiles`, `extensions`, `terminology`, and `examples` folders:
http://build.fhir.org/ig/HL7/fhir-shorthand/sushi.html#executing-sushi-from-command-line

Reported on SUSHI here: FHIR/sushi#256

**Comment by markkramerus** [comment]
Addressed and published.
