### ISSUE TITLE
having multiple slices of extension starting with the same string throws an error

### ISSUE THREAD

**Issue by 007vasy** [HL7/fhir-shorthand#72]
run `sushi .` on this to reproduce:
`Extension:      FastqPaired
Id:             FastqPaired
Title:          "Fastq Paired"
Description:    "Represents paired read data generated from sequencing performed on this specimen."

* extension contains
    forward 1..1 MS and
    forwardByteSize 0..1

* extension[forward] ^short = "Forward read file location"
* extension[forward].value[x] only string

* extension[forwardByteSize] ^short = "Forward file size in bytes"
* extension[forwardByteSize].value[x] only decimal`

**Comment by ngfreiter** [comment]
We are also tracking this in the SUSHI repo here https://github.com/FHIR/sushi/issues/531.

**Comment by 007vasy** [comment]
sorry I missed that
