### ISSUE TITLE
Re-prioiritize macros

### ISSUE THREAD

**Issue by DavidPyke** [HL7/fhir-shorthand#79]
Being able to create examples/instances for testing (like Connectathons) quickly without resorting to Excel or other systems would make my life easier.  Having macro substitution would make my life a happy place again.

**Comment by cmoesel** [comment]
Hi @DavidPyke.  I just noticed this issue hanging out here and was wondering if the new(ish) parameterize RuleSets scratches that itch for you or if you had something else in mind?

See: http://build.fhir.org/ig/HL7/fhir-shorthand/reference.html#parameterized-rule-sets

**Comment by DavidPyke** [comment]
That works.  You can close this
