### ISSUE TITLE
Choosing different FHIR versions

### ISSUE THREAD

**Issue by jduteau** [HL7/fhir-shorthand#82]
If I try to reference a later version of FHIR than 4.0.1, SUSHI currently stops with an error:
The sushi-config.yaml must specify FHIR R4 as a fhirVersion. Be sure to add "fhirVersion: 4.0.1" to the sushi-config.yaml file

I can work around this by copying a created IG.json file and manually changing the fhir version to 4.5.0.  It would be nice if SUSHI allowed any FHIR version with a major number of 4.

**Comment by cmoesel** [comment]
We want to be careful about supporting versions of FHIR that we've never tested SUSHI with -- as changes in FHIR might require changes in SUSHI as well (particularly changes to `StructureDefinition`, `ElementDefinition`, `ValueSet`, `CodeSystem`, and any core FHIR datatypes).

We actually plan to start looking at support for FHIR 4.5.0 in the next week or two.

**Comment by cmoesel** [comment]
Closing this as SUSHI now supports versions > 4.0.1.
