### ISSUE TITLE
Better document ValueSet filters for regex

### ISSUE THREAD

**Issue by cmoesel** [HL7/fhir-shorthand#94]
For VS filters that use the `regex` operator, FSH supports the `/myregex/` notation.  E.g.,
```
* codes from system MYSYSTEM where concept regex /^[Ff]oo/
```

It's been like this in the grammar since before 1.0.0, but we failed to document it in the reference.

**Comment by markkramerus** [comment]
Can you think of a realistic example?

**Comment by cmoesel** [comment]
No, but doing a quick survey, LOINC was the only code system I saw that defined a filter that used regex:
http://hl7.org/fhir/R4/loinc.html#4.3.3.8.1

Someone who knows LOINC well (not me) might be able to craft a reasonable example.  Might May or Carmela have an idea?  (I'd tag them, but GitHub isn't finding them).
